const fs=require('node:fs'),path=require('node:path'),https=require('node:https'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),APP=path.resolve(ROOT,'../sandlock-app');
const WEB='https://app.frontend.test:8796',API='https://api.backend.test:8796';
const results=[],errors=[],requests=[];let outage=false,dropCookies=false,oldWorker=false;
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
const server=https.createServer({key:fs.readFileSync(path.join(__dirname,'.runtime/key.pem')),cert:fs.readFileSync(path.join(__dirname,'.runtime/cert.pem'))},(req,res)=>{
 const url=new URL(req.url,WEB);requests.push({host:req.headers.host,path:url.pathname,method:req.method});
 if(req.headers.host==='api.backend.test:8796'){
  if(outage){res.writeHead(503,{'Access-Control-Allow-Origin':WEB,'Access-Control-Allow-Credentials':'true','Content-Type':'application/json'});res.end('{"error":"Temporary test outage"}');return;}
  const proxy=http.request({hostname:'127.0.0.1',port:8795,path:req.url,method:req.method,headers:{...req.headers,'x-forwarded-proto':'https','x-forwarded-host':req.headers.host}},r=>{const headers={...r.headers};if(dropCookies)delete headers['set-cookie'];res.writeHead(r.statusCode,headers);r.pipe(res);});proxy.on('error',()=>{res.writeHead(502);res.end();});req.pipe(proxy);return;
 }
 if(req.headers.host!=='app.frontend.test:8796'){res.writeHead(403);res.end();return;}
 if(url.pathname==='/user'||url.pathname.startsWith('/user/')){res.writeHead(307,{Location:url.pathname.replace(/^\/user\/?/,'/')+url.search});res.end();return;}
 if(oldWorker&&url.pathname==='/service-worker.js'){res.writeHead(200,{'Content-Type':'text/javascript','Cache-Control':'no-store'});res.end("self.addEventListener('install',e=>e.waitUntil(caches.open('sandlock-group7-v4-static').then(c=>c.put('/old.js',new Response('old'))).then(()=>self.skipWaiting())));self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));");return;}
 const file=path.resolve(APP,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));
 if(!file.startsWith(APP+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end('Not found');return;}
 let body=fs.readFileSync(file);if(path.basename(file)==='config.js')body=Buffer.from(body.toString().replace('https://sandlock-control-production.up.railway.app',API));
 res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(body);
});
async function test(name,fn,status='PASS'){try{await fn();results.push({name,status});console.log(status,name);}catch(e){results.push({name,status:'FAIL',error:e.stack});console.error('FAIL',name,e.message);throw e;}}
(async()=>{
 await new Promise(resolve=>server.listen(8796,'127.0.0.1',resolve));
 const browser=await chromium.launch({executablePath:process.env.SANDLOCK_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--no-proxy-server','--ignore-certificate-errors','--host-resolver-rules=MAP app.frontend.test 127.0.0.1,MAP api.backend.test 127.0.0.1','--test-third-party-cookie-phaseout']});
 try{
 const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 let navigations=0;page.on('framenavigated',f=>{if(f===page.mainFrame())navigations++;});
 const login='browser'+Date.now(),password='Local-Test-Password-487!';
 await test('B01 root/assets + stable anonymous UI',async()=>{await page.goto(WEB);await page.waitForSelector('[data-screen="login"].active');await page.waitForFunction(()=>!!window.SandLockAuth);const before=navigations;await page.waitForTimeout(1500);assert.equal(navigations,before);assert.equal(await page.locator('#authSubmit').innerText(),'Sign In');});
 await test('B02 actual cross-site registration/login/cookie/API',async()=>{await page.click('#createAccountMode');await page.fill('#accountLogin',login);await page.fill('#accountPassword',password);await page.fill('#fullName','Browser Test');await page.click('#authSubmit');await page.waitForFunction(()=>!!SandLockAuth.user);await page.waitForSelector('[data-screen="map"].active');const cookies=await context.cookies();const c=cookies.find(c=>c.name==='__Host-sandlock_user_session_v2');assert.ok(c?.secure&&c.httpOnly&&c.sameSite==='None'&&c.partitionKey);assert.ok(!(await page.evaluate(()=>document.cookie)).includes(c.value));assert.equal(await page.evaluate(async()=>{await SandLockReservations.request('/lockers');return true;}),true);});
 await test('B03 refresh restores cookie session',async()=>{await page.reload();await page.waitForSelector('[data-screen="map"].active');assert.equal(await page.evaluate(()=>SandLockAuth.user.login),login);await page.waitForFunction(()=>getComputedStyle(document.querySelector('[data-screen="map"]')).opacity==='1');await page.screenshot({path:path.join(__dirname,'.runtime/user-mobile.png'),fullPage:true,animations:'disabled'});});
 await test('B04 CSRF create/idempotent retry/complete through browser',async()=>{const r=await page.evaluate(async()=>{const now=Date.now(),p={bookingId:'browser-'+now,lockerId:'B',startTime:new Date(now).toISOString(),endTime:new Date(now+1800000).toISOString(),pin:'1234'};let denied;try{await SandLockBackend.request('/api/v1/reservations','POST',p);}catch(e){denied=e.status;}const first=await SandLockReservations.request('/reservations','POST',p),retry=await SandLockReservations.request('/reservations','POST',p);const end=await SandLockReservations.request('/reservations/'+p.bookingId+'/complete','POST',{expectedRevision:first.reservation.revision});return {denied,id:first.reservation.bookingId,retry:retry.reservation.bookingId,status:end.reservation.status};});assert.equal(r.denied,403);assert.equal(r.id,r.retry);assert.equal(r.status,'Completed');});
 await test('B05 real SW install and sensitive cache exclusion',async()=>{await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);const keys=await page.evaluate(async()=>{const names=await caches.keys();return (await Promise.all(names.map(async n=>(await(await caches.open(n)).keys()).map(r=>r.url)))).flat();});assert.ok(keys.length>15);assert.ok(keys.every(k=>!new URL(k).pathname.match(/^\/(auth|api)\//)&&new URL(k).origin===locationOrigin()),JSON.stringify(keys));function locationOrigin(){return WEB;}});
 await test('B06 offline shell and uncached asset valid 503',async()=>{await context.setOffline(true);await page.reload();await page.waitForSelector('[data-screen="login"].active');assert.match(await page.locator('#loginError').innerText(),/unavailable/);assert.equal(await page.evaluate(async()=>{const r=await fetch('/absent-offline.js');return r.status;}),503);await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.waitForSelector('[data-screen="map"].active');});
 await test('B07 delayed backend outage preserves session and recovery',async()=>{outage=true;await page.reload();await page.waitForSelector('[data-screen="login"].active');assert.match(await page.locator('#loginError').innerText(),/not been cleared/);outage=false;await page.evaluate(()=>{window.dispatchEvent(new Event('online'));window.dispatchEvent(new Event('focus'));});await page.waitForSelector('[data-screen="map"].active');},'SIMULATED');
 await test('B08 concurrent 401 stable sign-out without reload',async()=>{await page.evaluate(async()=>{await SandLockBackend.request('/auth/user/logout','POST',{},SandLockAuth.csrf);await Promise.allSettled([SandLockReservations.request('/lockers'),SandLockReservations.request('/reservations')]);});await page.waitForSelector('[data-screen="login"].active');const count=navigations;await page.waitForTimeout(4500);assert.equal(navigations,count);assert.equal(await page.evaluate(()=>SandLockAuth.user),null);});
 await test('B09 UI sign-in and logout remains stable/revoked',async()=>{await page.fill('#accountLogin',login);await page.fill('#accountPassword',password);await page.click('#authSubmit');await page.waitForSelector('[data-screen="map"].active');await page.evaluate(()=>document.querySelector('#logoutButton').click());await page.waitForSelector('[data-screen="login"].active');assert.equal(await page.evaluate(async()=>{try{await SandLockBackend.request('/auth/user/session');return 200;}catch(e){return e.status;}}),401);});
 await test('B10 blocked cookies fail visibly without signed-in UI',async()=>{dropCookies=true;await page.fill('#accountLogin',login);await page.fill('#accountPassword',password);await page.click('#authSubmit');await page.waitForFunction(()=>document.querySelector('#loginError').textContent.includes('secure session'));assert.equal(await page.evaluate(()=>SandLockAuth.user),null);dropCookies=false;},'SIMULATED');
 await test('B11 legacy /user route redirects to root; desktop/mobile shell',async()=>{await page.goto(WEB+'/user/');assert.equal(new URL(page.url()).pathname,'/');await page.waitForSelector('[data-screen="login"].active');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1366,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
 await test('B12 old worker/cache upgrades without reload loop',async()=>{const c=await browser.newContext({ignoreHTTPSErrors:true});const p=await c.newPage();oldWorker=true;await p.goto(WEB);await p.evaluate(()=>navigator.serviceWorker.ready);assert.ok((await p.evaluate(()=>caches.keys())).includes('sandlock-group7-v4-static'));oldWorker=false;await p.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});await p.waitForFunction(async()=>{const k=await caches.keys();return k.includes('sandlock-integration-v1-static')&&!k.includes('sandlock-group7-v4-static');});await p.reload();await p.waitForSelector('[data-screen="login"].active');await c.close();},'SIMULATED');
 await test('B13 no browser JS exceptions or wrong-origin API requests',async()=>{assert.deepEqual(errors,[]);assert.ok(!requests.some(r=>r.host==='app.frontend.test:8796'&&/^\/(auth|api)\//.test(r.path)));});
 await test('B14 first-party Owner login/dashboard/logout behind TLS proxy',async()=>{const owner=JSON.parse(fs.readFileSync(path.join(__dirname,'.runtime/browser-owner.json'),'utf8'));const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.setViewportSize({width:1366,height:900});await p.goto(API+'/');await p.waitForSelector('#ownerLogin');await p.fill('#ownerLogin',owner.login);await p.fill('#ownerPassword',owner.password);await p.click('#adminLogin button');await p.waitForURL(API+'/');await p.waitForFunction(()=>document.querySelector('#kRevenue')?.textContent.includes('EGP'));await p.screenshot({path:path.join(__dirname,'.runtime/owner-desktop.png'),fullPage:true});const cookie=(await context.cookies()).find(c=>c.name==='sandlock_admin_session');assert.ok(cookie.secure&&cookie.httpOnly&&cookie.sameSite==='Lax'&&!cookie.partitionKey);await p.click('#adminLogout');await p.waitForURL(API+'/static/login.html');assert.deepEqual(errors,[]);await p.close();});
 await context.close();
 }finally{await browser.close();server.close();fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify(results,null,2));}
})().catch(e=>{console.error(e.stack);server.close();process.exitCode=1;});
