const fs=require('node:fs'),path=require('node:path'),https=require('node:https'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),APP=path.resolve(ROOT,'../sandlock-app');
const WEB='https://app.frontend.test:8796',API='https://api.backend.test:8796';
const rewrites=JSON.parse(fs.readFileSync(path.join(APP,'vercel.json'),'utf8')).rewrites;
const userProxy=p=>rewrites.some(r=>new RegExp('^'+r.source.replace(/:\w+\(([^)]+)\)/g,'($1)')+'$').test(p));
const results=[],errors=[],requests=[];let outage=false,dropCookies=false,oldWorker=false;
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
const server=https.createServer({key:fs.readFileSync(path.join(__dirname,'.runtime/key.pem')),cert:fs.readFileSync(path.join(__dirname,'.runtime/cert.pem'))},(req,res)=>{
 const url=new URL(req.url,WEB);requests.push({host:req.headers.host,path:url.pathname,method:req.method});
 if(req.headers.host==='api.backend.test:8796'||(req.headers.host==='app.frontend.test:8796'&&userProxy(url.pathname))){
  if(outage){res.writeHead(503,{'Access-Control-Allow-Origin':WEB,'Access-Control-Allow-Credentials':'true','Content-Type':'application/json'});res.end('{"error":"Temporary test outage"}');return;}
  const proxy=http.request({hostname:'127.0.0.1',port:8795,path:req.url,method:req.method,headers:{...req.headers,'x-forwarded-proto':'https','x-forwarded-host':'api.backend.test:8796'}},r=>{const headers={...r.headers};if(dropCookies)delete headers['set-cookie'];res.writeHead(r.statusCode,headers);r.pipe(res);});proxy.on('error',()=>{res.writeHead(502);res.end();});req.pipe(proxy);return;
 }
 if(req.headers.host!=='app.frontend.test:8796'){res.writeHead(403);res.end();return;}
 if(url.pathname==='/user'||url.pathname.startsWith('/user/')){res.writeHead(307,{Location:url.pathname.replace(/^\/user\/?/,'/')+url.search});res.end();return;}
 if(oldWorker&&url.pathname==='/service-worker.js'){res.writeHead(200,{'Content-Type':'text/javascript','Cache-Control':'no-store'});res.end("self.addEventListener('install',e=>e.waitUntil(caches.open('sandlock-group7-v4-static').then(c=>c.put('/old.js',new Response('old'))).then(()=>self.skipWaiting())));self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));");return;}
 const file=path.resolve(APP,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));
 if(!file.startsWith(APP+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end('Not found');return;}
 const body=fs.readFileSync(file);
 res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(body);
});
async function test(name,fn,status='PASS'){try{await fn();results.push({name,status});console.log(status,name);}catch(e){results.push({name,status:'FAIL',error:e.stack});console.error('FAIL',name,e.message);throw e;}}
(async()=>{
 await new Promise(resolve=>server.listen(8796,'127.0.0.1',resolve));
 const browser=await chromium.launch({executablePath:process.env.SANDLOCK_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--no-proxy-server','--ignore-certificate-errors','--host-resolver-rules=MAP app.frontend.test 127.0.0.1,MAP api.backend.test 127.0.0.1','--test-third-party-cookie-phaseout']});
 try{
 const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 let navigations=0;page.on('framenavigated',f=>{if(f===page.mainFrame())navigations++;});
 const login='browser'+Date.now(),password='Local-Test-Password-487!';
 await test('B01 root/assets + stable anonymous UI',async()=>{await page.goto(WEB);await page.waitForSelector('[data-screen="login"].active');await page.waitForFunction(()=>!!window.SandLockAuth);const before=navigations;await page.waitForTimeout(1500);assert.equal(navigations,before);assert.equal(await page.locator('#authSubmit').innerText(),'Sign In');});
 await test('B02 same-origin registration/login/cookie/API with third-party cookies blocked',async()=>{await page.click('#createAccountMode');await page.fill('#accountLogin',login);await page.fill('#accountPassword',password);await page.fill('#fullName','Browser Test');await page.fill('#mobile','01012345678');await page.click('#authSubmit');await page.waitForFunction(()=>!!SandLockAuth.user);await page.waitForSelector('[data-screen="map"].active');const cookies=await context.cookies();const c=cookies.find(c=>c.name==='__Host-sandlock_user_session_v3');assert.ok(c?.secure&&c.httpOnly&&c.sameSite==='Lax'&&!c.partitionKey&&c.domain==='app.frontend.test');assert.ok(!(await page.evaluate(()=>document.cookie)).includes(c.value));assert.equal(await page.evaluate(async()=>{await SandLockReservations.request('/lockers');return true;}),true);});
 await test('B03 refresh restores cookie session',async()=>{await page.reload();await page.waitForSelector('[data-screen="map"].active');assert.equal(await page.evaluate(()=>SandLockAuth.user.login),login);await page.waitForFunction(()=>getComputedStyle(document.querySelector('[data-screen="map"]')).opacity==='1');await page.screenshot({path:path.join(__dirname,'.runtime/user-mobile.png'),fullPage:true,animations:'disabled'});});
 await test('B04 CSRF create/idempotent retry/complete through browser',async()=>{const r=await page.evaluate(async()=>{const now=Date.now(),p={bookingId:'browser-'+now,lockerId:'B',startTime:new Date(now).toISOString(),endTime:new Date(now+1800000).toISOString(),pin:'1234'};let denied;try{await SandLockBackend.request('/api/v1/reservations','POST',p);}catch(e){denied=e.status;}const first=await SandLockReservations.request('/reservations','POST',p),retry=await SandLockReservations.request('/reservations','POST',p);const end=await SandLockReservations.request('/reservations/'+p.bookingId+'/complete','POST',{expectedRevision:first.reservation.revision});return {denied,id:first.reservation.bookingId,retry:retry.reservation.bookingId,status:end.reservation.status};});assert.equal(r.denied,403);assert.equal(r.id,r.retry);assert.equal(r.status,'Completed');});
 await test('N-B01 notification history/unread/read/local timestamp/refresh',async()=>{require('node:child_process').execFileSync('python',['-B',path.join(__dirname,'inject_notification.py'),login],{cwd:ROOT});await page.click('#notificationBell');await page.waitForFunction(()=>document.querySelectorAll('.locker-notification').length===3);assert.equal(await page.locator('#notificationCount').innerText(),'3');assert.ok((await page.locator('.locker-notification').first().innerText()).includes('Locker A'));assert.ok(await page.locator('.locker-notification time').first().getAttribute('datetime'));await page.locator('.locker-notification button').first().click();await page.waitForFunction(()=>document.querySelector('#notificationCount').textContent==='2');await page.screenshot({path:path.join(__dirname,'.runtime/notifications-mobile.png'),fullPage:true,animations:'disabled'});await page.setViewportSize({width:1366,height:900});await page.screenshot({path:path.join(__dirname,'.runtime/notifications-desktop.png'),fullPage:true,animations:'disabled'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForSelector('[data-screen="notifications"].active');await page.waitForFunction(()=>document.querySelectorAll('.locker-notification').length===3);await page.click('[data-screen="notifications"] [data-go="map"]');},'SIMULATED');
 await test('B05 real SW install and sensitive cache exclusion',async()=>{await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);const keys=await page.evaluate(async()=>{const names=await caches.keys();return (await Promise.all(names.map(async n=>(await(await caches.open(n)).keys()).map(r=>r.url)))).flat();});assert.ok(keys.length>15);assert.ok(keys.every(k=>!new URL(k).pathname.match(/^\/(auth|api)\//)&&new URL(k).origin===locationOrigin()),JSON.stringify(keys));function locationOrigin(){return WEB;}});
 await test('B06 offline shell and uncached asset valid 503',async()=>{await context.setOffline(true);await page.reload();await page.waitForSelector('[data-screen="login"].active');assert.match(await page.locator('#loginError').innerText(),/unavailable/);assert.equal(await page.evaluate(async()=>{const r=await fetch('/absent-offline.js');return r.status;}),503);await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.waitForSelector('[data-screen="map"].active');});
 await test('B07 delayed backend outage preserves session and recovery',async()=>{outage=true;await page.reload();await page.waitForSelector('[data-screen="login"].active');assert.match(await page.locator('#loginError').innerText(),/not been cleared/);outage=false;await page.evaluate(()=>{window.dispatchEvent(new Event('online'));window.dispatchEvent(new Event('focus'));});await page.waitForSelector('[data-screen="map"].active');},'SIMULATED');
 await test('B08 concurrent 401 stable sign-out without reload',async()=>{await page.evaluate(async()=>{await SandLockBackend.request('/auth/user/logout','POST',{},SandLockAuth.csrf);await Promise.allSettled([SandLockReservations.request('/lockers'),SandLockReservations.request('/reservations')]);});await page.waitForSelector('[data-screen="login"].active');const count=navigations;await page.waitForTimeout(4500);assert.equal(navigations,count);assert.equal(await page.evaluate(()=>SandLockAuth.user),null);});
 await test('B09 UI sign-in and logout remains stable/revoked',async()=>{await page.fill('#accountLogin',login);await page.fill('#accountPassword',password);await page.click('#authSubmit');await page.waitForSelector('[data-screen="map"].active');await page.evaluate(()=>document.querySelector('#logoutButton').click());await page.waitForSelector('[data-screen="login"].active');assert.equal(await page.locator('.locker-notification').count(),0);assert.equal(await page.evaluate(async()=>{try{await SandLockBackend.request('/auth/user/session');return 200;}catch(e){return e.status;}}),401);});
 await test('B10 blocked cookies fail visibly without signed-in UI',async()=>{dropCookies=true;await page.fill('#accountLogin',login);await page.fill('#accountPassword',password);await page.click('#authSubmit');await page.waitForFunction(()=>document.querySelector('#loginError').textContent.includes('secure session'));assert.equal(await page.evaluate(()=>SandLockAuth.user),null);dropCookies=false;},'SIMULATED');
 await test('B11 legacy /user route redirects to root; desktop/mobile shell',async()=>{await page.goto(WEB+'/user/');assert.equal(new URL(page.url()).pathname,'/');await page.waitForSelector('[data-screen="login"].active');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1366,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
 await test('B12 old worker/cache upgrades without reload loop',async()=>{const c=await browser.newContext({ignoreHTTPSErrors:true});const p=await c.newPage();oldWorker=true;await p.goto(WEB);await p.evaluate(()=>navigator.serviceWorker.ready);assert.ok((await p.evaluate(()=>caches.keys())).includes('sandlock-group7-v4-static'));oldWorker=false;await p.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});await p.waitForFunction(async()=>{const k=await caches.keys();return k.includes('sandlock-same-origin-v1-static')&&!k.includes('sandlock-group7-v4-static');});await p.reload();await p.waitForSelector('[data-screen="login"].active');await c.close();},'SIMULATED');
 await test('B13 no browser JS exceptions or wrong-origin API requests',async()=>{assert.deepEqual(errors,[]);assert.ok(requests.some(r=>r.host==='app.frontend.test:8796'&&r.path==='/auth/user/login'));assert.ok(!requests.some(r=>r.host==='api.backend.test:8796'&&/^\/(auth|api)\//.test(r.path)));for(const path of ['/auth/admin/login','/api/overview','/api/v1/legacy-reservations/import','/download/database.xlsx'])assert.equal(await page.evaluate(async path=>(await fetch(path)).status,path),404);});
 await test('B14 first-party Owner login/dashboard/logout behind TLS proxy',async()=>{const owner=JSON.parse(fs.readFileSync(path.join(__dirname,'.runtime/browser-owner.json'),'utf8'));const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.setViewportSize({width:1366,height:900});await p.goto(API+'/');await p.waitForSelector('#ownerLogin');await p.fill('#ownerLogin',owner.login);await p.fill('#ownerPassword',owner.password);await p.click('#adminLogin button');await p.waitForURL(API+'/');await p.waitForFunction(()=>document.querySelector('#kRevenue')?.textContent.includes('EGP'));await p.screenshot({path:path.join(__dirname,'.runtime/owner-desktop.png'),fullPage:true});const cookie=(await context.cookies()).find(c=>c.name==='sandlock_admin_session');assert.ok(cookie.secure&&cookie.httpOnly&&cookie.sameSite==='Lax'&&!cookie.partitionKey);await p.click('#adminLogout');await p.waitForURL(API+'/static/login.html');assert.deepEqual(errors,[]);await p.close();});
 await test('N-B02 unsupported browser/denied permission/no startup prompt',async()=>{
  for(const unsupported of [true,false]){const c=await browser.newContext({ignoreHTTPSErrors:true});await c.addInitScript(value=>{window.permissionRequests=0;if(value)delete window.PushManager;else{Object.defineProperty(Notification,'permission',{get:()=> 'denied'});Notification.requestPermission=async()=>{window.permissionRequests++;return 'denied';};}},unsupported);const p=await c.newPage();await p.goto(WEB);await p.waitForSelector('[data-screen="login"].active');await p.fill('#accountLogin',login);await p.fill('#accountPassword',password);await p.click('#authSubmit');await p.waitForSelector('[data-screen="map"].active');await p.click('#notificationBell');await p.waitForFunction(()=>/not supported|blocked/.test(document.querySelector('#pushState').textContent));assert.equal(await p.evaluate(()=>window.permissionRequests),0);assert.ok(await p.locator('#enableLockerAlerts').isDisabled());await c.close();}
 },'SIMULATED');
 await test('N-B03 separate account cannot see previous history',async()=>{await page.goto(WEB);await page.waitForSelector('[data-screen="login"].active');await page.click('#createAccountMode');await page.fill('#accountLogin',login+'b');await page.fill('#accountPassword',password);await page.fill('#fullName','Second Browser User');await page.fill('#mobile','01112345678');await page.click('#authSubmit');await page.waitForSelector('[data-screen="map"].active');await page.click('#notificationBell');await page.waitForFunction(()=>document.querySelector('#pushState').textContent.includes('not configured'));assert.equal(await page.locator('.locker-notification').count(),0);assert.ok(await page.locator('#notificationEmpty').isVisible());await page.evaluate(async({login,password})=>{await SandLockAuth.request('login',{login,password});}, {login,password});await page.waitForFunction(()=>document.querySelectorAll('.locker-notification').length===3);await page.evaluate(async({login,password})=>{await SandLockAuth.request('login',{login:login+'b',password});}, {login,password});await page.waitForFunction(()=>document.querySelectorAll('.locker-notification').length===0);});
 await test('N-B04 explicit enable/disable/subscription failure and worker binding',async()=>{
  const c=await browser.newContext({ignoreHTTPSErrors:true});const pub=require('node:crypto').createECDH('prime256v1').generateKeys().toString('base64url');
  await c.addInitScript(()=>{let permission='default';window.permissionRequests=0;window.localPush=null;Object.defineProperty(Notification,'permission',{get:()=>permission});Notification.requestPermission=async()=>{window.permissionRequests++;permission='granted';return permission;};PushManager.prototype.getSubscription=async()=>window.localPush;PushManager.prototype.subscribe=async options=>{if(window.failSubscription)throw Error('Injected failure');window.localPush={endpoint:'https://fcm.googleapis.com/fcm/send/local-test',options,toJSON:()=>({endpoint:'https://fcm.googleapis.com/fcm/send/local-test',keys:{p256dh:'mock',auth:'mock'}}),unsubscribe:async()=>{window.localPush=null;return true;}};return window.localPush;};});
  const p=await c.newPage();await p.goto(WEB);await p.waitForSelector('[data-screen="login"].active');await p.fill('#accountLogin',login);await p.fill('#accountPassword',password);await p.click('#authSubmit');await p.waitForSelector('[data-screen="map"].active');await p.evaluate(()=>navigator.serviceWorker.ready);const data=await p.evaluate(()=>SandLockReservations.request('/notifications'));let linked=false;
  const headers={'Access-Control-Allow-Origin':WEB,'Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type, X-CSRF-Token','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};
  await c.route('**/api/v1/notifications',route=>route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify({...data,push:{enabled:true,publicKey:pub,subscriptions:linked?[{id:'a'.repeat(64),channel:'local_test_binding_channel_12345'}]:[]}})}));
  await c.route('**/api/v1/push-subscriptions**',route=>{linked=!route.request().url().endsWith('/remove');return route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify({id:'a'.repeat(64),channel:'local_test_binding_channel_12345',ok:true})});});
  await p.click('#notificationBell');await p.click('#refreshNotifications');await p.waitForFunction(()=>!document.querySelector('#enableLockerAlerts').disabled);assert.equal(await p.evaluate(()=>window.permissionRequests),0);await p.click('#enableLockerAlerts');await p.waitForFunction(()=>document.querySelector('#pushState').textContent.includes('enabled on this device'));assert.equal(await p.evaluate(()=>window.permissionRequests),1);await p.click('#disableLockerAlerts');await p.waitForFunction(()=>document.querySelector('#pushState').textContent.includes('disabled on this device'));await p.evaluate(()=>window.failSubscription=true);await p.click('#enableLockerAlerts');await p.waitForFunction(()=>document.querySelector('#pushState').textContent.includes('Could not enable'));assert.equal(await p.evaluate(()=>window.permissionRequests),1);await c.close();
 },'SIMULATED');
 await context.close();
 }finally{await browser.close();server.close();fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify(results,null,2));}
})().catch(e=>{console.error(e.stack);server.close();process.exitCode=1;});
