const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const APP=path.resolve(__dirname,'../../sandlock-app');
const source=name=>fs.readFileSync(path.join(APP,name),'utf8');
function context(extra={}){const c=vm.createContext({URL,Response,Request,Headers,AbortController,Event,setTimeout,clearTimeout,console,location:{origin:'https://app.example'},...extra});c.window=c;return c;}
function load(c,name){vm.runInContext(source(name),c,{filename:name});}
test('central URL and credentialed CSRF transport',async()=>{let sent;const c=context({SANDLOCK_CONFIG:{backendOrigin:'https://backend.example'},fetch:async(url,options)=>{sent={url,options};return Response.json({ok:true});}});load(c,'backend-client.js');await c.SandLockBackend.request('/api/v1/reservations','POST',{bookingId:'test'},'csrf');assert.equal(sent.url,'https://app.example/api/v1/reservations');assert.equal(sent.options.credentials,'same-origin');assert.equal(sent.options.cache,'no-store');assert.equal(sent.options.headers['X-CSRF-Token'],'csrf');assert.throws(()=>c.SandLockBackend.url('//untrusted.example'));});
test('remote configuration cannot redirect session transport',()=>{const c=context({SANDLOCK_CONFIG:{backendOrigin:'https://evil.example'}});load(c,'backend-client.js');assert.equal(c.SandLockBackend.url('/auth/user/session'),'https://app.example/auth/user/session');for(const p of ['//evil.example','/\\\\evil.example','https://evil.example','/auth/user/session#bad'])assert.throws(()=>c.SandLockBackend.url(p));});
test('bad backend response distinguished',async()=>{const c=context({SANDLOCK_CONFIG:{backendOrigin:'https://backend.example'},fetch:async()=>new Response('invalid')});load(c,'backend-client.js');await assert.rejects(c.SandLockBackend.request('/auth/user/session'),e=>e.status===502);});
test('obsolete auth response cannot replace new session',async()=>{let pending;const c=context({SandLockBackend:{request:()=>new Promise(resolve=>pending=resolve)}});load(c,'auth-client.js');const work=c.SandLockAuth.request('session');c.SandLockAuth.reset();c.SandLockAuth.user={userId:'new'};pending({data:{user:{userId:'old'},csrf:'old'}});await assert.rejects(work,e=>e.code==='SUPERSEDED');assert.equal(c.SandLockAuth.user.userId,'new');});
test('simultaneous current 401 signals expire once',async()=>{let events=0;const c=context({dispatchEvent:()=>events++,SandLockBackend:{request:async()=>{const e=new Error('expired');e.status=401;throw e;}}});load(c,'auth-client.js');load(c,'reservation-client.js');c.SandLockAuth.user={userId:'a'};c.SandLockAuth.csrf='a';await Promise.allSettled([c.SandLockReservations.request('/lockers'),c.SandLockReservations.request('/reservations')]);assert.equal(events,1);assert.equal(c.SandLockAuth.user,null);});
test('old account 401 does not log out replacement account',async()=>{let reject,events=0;const c=context({dispatchEvent:()=>events++,SandLockBackend:{request:()=>new Promise((_,r)=>reject=r)}});load(c,'auth-client.js');load(c,'reservation-client.js');c.SandLockAuth.user={userId:'old'};c.SandLockAuth.csrf='old';const work=c.SandLockReservations.request('/reservations');c.SandLockAuth.reset();c.SandLockAuth.user={userId:'new'};c.SandLockAuth.csrf='new';const e=new Error('expired');e.status=401;reject(e);await assert.rejects(work);assert.equal(c.SandLockAuth.user.userId,'new');assert.equal(events,0);});
function worker({cacheFail=false,networkFail=false}={}){const handlers={},cached=new Map();const c=context({self:{location:{origin:'https://app.example'},addEventListener:(n,f)=>handlers[n]=f,skipWaiting:async()=>{},clients:{claim:async()=>{}}},caches:{open:async()=>{if(cacheFail)throw Error('storage denied');return {match:async k=>cached.get(k),put:async()=>{},addAll:async()=>{}};},keys:async()=>[],delete:async()=>true},fetch:async()=>{if(networkFail)throw Error('offline');return new Response('network');}});load(c,'service-worker.js');return {handlers,cached};}
async function fetchSW(w,url,mode='cors'){let result;w.handlers.fetch({request:{url,method:'GET',mode},respondWith:r=>result=r});return result;}
test('SW dynamic and cross-origin requests not intercepted',async()=>{const w=worker();for(const url of ['https://api.example/auth/user/session','https://app.example/auth/user/session','https://app.example/api/v1/lockers','https://app.example/download/report'])assert.equal(await fetchSW(w,url),undefined);});
test('SW uncached offline asset gives valid Response',async()=>{const r=await fetchSW(worker({networkFail:true}),'https://app.example/missing.js');assert.ok(r instanceof Response);assert.equal(r.status,503);});
test('SW offline navigation without cache gives valid Response',async()=>{const r=await fetchSW(worker({networkFail:true}),'https://app.example/','navigate');assert.ok(r instanceof Response);assert.equal(r.status,503);});
test('SW cache failure still returns network Response',async()=>{const r=await fetchSW(worker({cacheFail:true}),'https://app.example/app.js');assert.equal(await r.text(),'network');});
test('SW cache plus network failure still returns Response',async()=>{for(const [url,mode] of [['https://app.example/app.js','cors'],['https://app.example/','navigate']])assert.equal((await fetchSW(worker({cacheFail:true,networkFail:true}),url,mode)).status,503);});
test('SW legacy path uses explicit navigation redirect',async()=>{const r=await fetchSW(worker(),'https://app.example/user/','navigate');assert.equal(r.status,307);assert.equal(r.headers.get('Location'),'https://app.example/');});
test('manifest/HTML/CSS/worker local assets exist and versions align',()=>{const manifest=JSON.parse(source('manifest.webmanifest'));assert.equal(manifest.start_url,'./');assert.equal(manifest.scope,'./');for(const i of manifest.icons)assert.ok(fs.existsSync(path.join(APP,i.src)),i.src);const html=source('index.html');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){const url=m[1].split('?')[0];if(url==='/'||/^https?:|^data:/.test(url))continue;assert.ok(fs.existsSync(path.join(APP,url)),url);}for(const m of source('service-worker.js').split('];')[0].matchAll(/'\.\/([^']+)'/g)){assert.ok(fs.existsSync(path.join(APP,m[1].split('?')[0])),m[1]);}for(const m of source('styles.css').matchAll(/url\(['"]?([^)'"\s]+)['"]?\)/g)){if(!m[1].startsWith('data:'))assert.ok(fs.existsSync(path.join(APP,m[1])),m[1]);}assert.ok(!html.includes('group7-4'));assert.ok(!source('service-worker.js').includes('group7-4'));});
test('Vercel proxies only enumerated User paths to fixed Railway origin',()=>{const c=JSON.parse(source('vercel.json'));assert.equal(c.rewrites.length,29);assert.ok(c.redirects.every(r=>r.source.startsWith('/user')));const matches=p=>c.rewrites.some(r=>new RegExp('^'+r.source.replace(/:\w+\(([^)]+)\)/g,'($1)')+'$').test(p));for(const r of c.rewrites){assert.ok(r.destination.startsWith('https://sandlock-control-production.up.railway.app/'));assert.ok(!r.source.includes('*'));}for(const p of ['/auth/user/login','/api/v1/notifications','/api/v1/notifications/abc123/read','/api/v1/push-subscriptions/remove','/api/v1/reservations/booking-1/cancel','/api/v1/reservations/booking-1/extend','/api/v1/feedback','/api/v1/reservations/booking-1/feedback'])assert.ok(matches(p),p);for(const p of ['/auth/admin/login','/api/overview','/api/cmd/unlock','/api/v1/legacy-reservations/import','/download/database.xlsx','/api/v1/reservations/x/reveal-pin','/api/v1/events/unknown','/api/v1/reservations/x/y/cancel'])assert.ok(!matches(p),p);});

test('same-origin notification pagination preserves query',()=>{const c=context();load(c,'backend-client.js');assert.equal(c.SandLockBackend.url('/api/v1/notifications?before=123'),'https://app.example/api/v1/notifications?before=123');});

test('registration validation copy uses 8-character password minimum and exact 11-digit mobile',()=>{const js=source('app.js'),html=source('index.html');assert.ok(js.includes("credentials.password.length<8"));assert.ok(js.includes("Use a password of 8–128 characters."));assert.ok(js.includes("!/^[0-9]{11}$/.test(mobile.value)"));assert.ok(js.includes("Mobile number must be exactly 11 digits."));assert.ok(html.includes('id="mobile"'));assert.ok(html.includes('Mobile number must be exactly 11 digits.'));});
