const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const code=fs.readFileSync(path.resolve(__dirname,'../../sandlock-app/service-worker.js'),'utf8');
function setup(){const handlers={},store=new Map([['binding','channel_for_account_a_123456']]),shown=[],opened=[],messages=[];const c=vm.createContext({URL,Response,Intl,Date,Promise,self:{location:{origin:'https://app.example'},addEventListener:(n,f)=>handlers[n]=f,registration:{showNotification:async(title,options)=>shown.push({title,...options}),getNotifications:async()=>shown.map(n=>({close:()=>n.closed=true}))},clients:{matchAll:async()=>[],openWindow:async url=>opened.push(url)}}});vm.runInContext(code,c);c.mockStore=async(mode,fn)=>{const result=fn({get:k=>({result:store.get(k)}),put:(v,k)=>{store.set(k,v);return {result:k};},openCursor:()=>({})});return result?.result;};vm.runInContext('alertStore=mockStore',c);async function push(data){let work;handlers.push({data:{json:()=>data},waitUntil:p=>work=p});await work;}async function message(type,channel){let work;handlers.message({data:{type,channel},source:{url:'https://app.example/'},ports:[{postMessage:x=>messages.push(x)}],waitUntil:p=>work=p});await work;}return {handlers,store,shown,opened,messages,push,message};}
const payload={notificationId:'1'.repeat(32),lockerId:'B',eventType:'door-opened',timestamp:'2026-09-22T17:35:04.000Z',channel:'channel_for_account_a_123456'};
test('push message identifies exact locker/date/time and no booking/PIN',async()=>{const t=setup();await t.push(payload);assert.equal(t.shown.length,1);assert.match(t.shown[0].body,/Locker B opened on/);assert.match(t.shown[0].body,/2026/);assert.match(t.shown[0].body,/35:04/);assert.equal(t.shown[0].data.screen,'notifications');assert.ok(!t.shown[0].body.includes('Locker A'));});
test('duplicate simultaneous push events displayed once',async()=>{const t=setup();await Promise.all([t.push(payload),t.push(payload)]);assert.equal(t.shown.length,1);});
test('separate open events and closed event retained',async()=>{const t=setup();await t.push(payload);await t.push({...payload,notificationId:'2'.repeat(32),eventType:'door-closed'});await t.push({...payload,notificationId:'3'.repeat(32)});assert.equal(t.shown.length,3);assert.match(t.shown[1].body,/Locker B closed/);});
test('logout clears binding/closes visible alerts and rejects delayed push',async()=>{const t=setup();await t.push(payload);await t.message('sandlock-clear-alerts');assert.ok(t.shown[0].closed);await t.push({...payload,notificationId:'2'.repeat(32)});assert.equal(t.shown.length,1);});
test('account replacement cannot display previous channel data',async()=>{const t=setup();await t.message('sandlock-bind-alerts','channel_for_account_b_123456');await t.push(payload);assert.equal(t.shown.length,0);});
test('malformed push data is ignored',async()=>{const t=setup();for(const value of [null,{}, {...payload,lockerId:'<script>'},{...payload,timestamp:'invalid'},{...payload,eventType:'command'}])await t.push(value);assert.equal(t.shown.length,0);});
test('click opens only local notification history, ignores supplied URL',async()=>{const t=setup();let work;t.handlers.notificationclick({notification:{data:{screen:'notifications',url:'https://evil.invalid'},close(){}},waitUntil:p=>work=p});await work;assert.deepEqual(t.opened,['./#notifications']);});
test('subscription expiration clears opaque binding',async()=>{const t=setup();let work;t.handlers.pushsubscriptionchange({waitUntil:p=>work=p});await work;assert.equal(t.store.get('binding'),null);});
